---
apiVersion: v1
kind: ConfigMap
metadata:
  name: asciinema
  namespace: asciinema
data:
  URL_SCHEME: 'http'
  URL_HOST: 'asciinema.localhost'
  URL_PORT: '80'
  MAILNAME: 'something.something.tld'
  SMARTHOST_ADDRESS: 'something.something.tld'
  SMARTHOST_PORT: '587'
  GMAIL_USER: ''
  GMAIL_PASSWORD: ''
  DISABLE_IPV6: 'true'
  RELAY_NETWORKS: ':10.0.0.0/8'
